{
    "schemes": [
        "https"
    ],
    "swagger": "2.0",
    "info": {
        "title": "Tink API",
        "version": "1.0.0"
    },
    "host": "api.us.tink.com",
    "paths": {
        "/api/v1/account-verification-reports/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch report JSON data based on a report identifier.",
                "tags": [
                    "Data v1.Account Verification",
                    "REGION.US"
                ],
                "summary": "Get Account Verification Report",
                "operationId": "getReport"
            }
        },
        "/api/v1/account-verification-reports/{id}/pdf": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "account-verification-reports:read"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "account-verification-reports:read"
                        ]
                    }
                ],
                "description": "Fetch a PDF report based on the data returned in the Account Verification report API.",
                "tags": [
                    "Data v1.Account Verification"
                ],
                "summary": "Get Account Verification PDF Report",
                "operationId": "getAsPdf"
            }
        },
        "/api/v1/accounts/list": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "accounts:read"
                        ]
                    }
                ],
                "description": "Returns an object with a list of the authenticated user's accounts.",
                "tags": [
                    "Data v1.Account"
                ],
                "summary": "List accounts",
                "operationId": "listAccounts"
            }
        },
        "/api/v1/accounts/{id}": {
            "put": {
                "security": [
                    {
                        "OAuth2User": [
                            "accounts:write"
                        ]
                    }
                ],
                "description": "Updates mutable properties of an account. The following properties are possible to update: accountExclusion, accountNumber, excluded, favored, name, type",
                "tags": [
                    "Data v1.Account",
                    "ENTERPRISE"
                ],
                "summary": "Update an Account",
                "operationId": "update"
            }
        },
        "/api/v1/accounts/{id}/balances": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "balances:read"
                        ]
                    }
                ],
                "description": "Returns an object with the account’s balances.",
                "tags": [
                    "Data v1.Account",
                    "ENTERPRISE",
                    "BETA"
                ],
                "summary": "Get balances for account",
                "operationId": "getBalances"
            }
        },
        "/api/v1/authorization/hooks": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "user:web_hooks"
                        ]
                    }
                ],
                "description": "(DEPRECATED) List the registered webhooks for the given user.",
                "tags": [
                    "Events v1.Webhook",
                    "ENTERPRISE"
                ],
                "summary": "List Webhooks",
                "operationId": "listHooks",
                "deprecated": true
            },
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "user:web_hooks"
                        ]
                    }
                ],
                "description": "(DEPRECATED) Create a new webhook for the authenticated user, giving the possibility to get pushed updates for certain events. Creating a new webhook will remove the existing one.",
                "tags": [
                    "Events v1.Webhook",
                    "ENTERPRISE"
                ],
                "summary": "Create Webhook",
                "operationId": "createHook",
                "deprecated": true
            }
        },
        "/api/v1/authorization/hooks/{id}": {
            "delete": {
                "security": [
                    {
                        "OAuth2": [
                            "user:web_hooks"
                        ]
                    }
                ],
                "description": "(DEPRECATED) Delete the webhook of the given ID.",
                "tags": [
                    "Events v1.Webhook",
                    "ENTERPRISE"
                ],
                "summary": "Delete Webhook",
                "operationId": "deleteHook",
                "deprecated": true
            }
        },
        "/api/v1/balance-refresh": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "balance-refresh"
                        ]
                    }
                ],
                "description": "Request a balance refresh for an account",
                "tags": [
                    "Connectivity v1.Balance Refresh",
                    "BETA",
                    "REGION.US"
                ],
                "summary": "Request Balance Refresh",
                "operationId": "triggerBalanceRefresh_1"
            }
        },
        "/api/v1/balance-refresh/{refreshId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "balance-refresh:readonly"
                        ]
                    }
                ],
                "description": "Get the status of a balance refresh.",
                "tags": [
                    "Connectivity v1.Balance Refresh",
                    "BETA",
                    "REGION.US"
                ],
                "summary": "Get Balance Refresh Status",
                "operationId": "fetchBalanceRefreshStatus"
            }
        },
        "/api/v1/budgets": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:read"
                        ]
                    }
                ],
                "description": "List all budgets for the user.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "List budgets",
                "operationId": "listBudgets"
            }
        },
        "/api/v1/budgets/one-off": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:write"
                        ]
                    }
                ],
                "description": "Creates a budget for a specific date interval.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Create one-off budget",
                "operationId": "createOneOffBudget"
            }
        },
        "/api/v1/budgets/recommended": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:read"
                        ]
                    }
                ],
                "description": "List budget recommendations based on spending patterns.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "List recommended budgets",
                "operationId": "recommendedBudget"
            }
        },
        "/api/v1/budgets/recurring": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:write"
                        ]
                    }
                ],
                "description": "Creates a recurring budget with a set periodicity.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Create recurring budget",
                "operationId": "createRecurringBudget"
            }
        },
        "/api/v1/budgets/summaries": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:read"
                        ]
                    }
                ],
                "description": "List all budgets for the user including current period for each budget.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "List budgets with summaries",
                "operationId": "listBudgetWithSummaries"
            }
        },
        "/api/v1/budgets/{id}": {
            "put": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:write"
                        ]
                    }
                ],
                "description": "Updates the specified budget.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Update budget",
                "operationId": "updateBudget"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:write"
                        ]
                    }
                ],
                "description": "Deletes the specified budget.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Delete budget",
                "operationId": "deleteBudget"
            }
        },
        "/api/v1/budgets/{id}/archive": {
            "put": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:write"
                        ]
                    }
                ],
                "description": "Archives the specified budget.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Archive budget",
                "operationId": "archiveBudget"
            }
        },
        "/api/v1/budgets/{id}/details": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:read"
                        ]
                    }
                ],
                "description": "Get the specified budget and its periods within the start and end\ndates. The date parameters are inclusive, thus specifying a date in\nthe middle of a period will include the complete period amounts.\n",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Get budget details",
                "operationId": "getBudgetDetails"
            }
        },
        "/api/v1/budgets/{id}/transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "budgets:read"
                        ]
                    }
                ],
                "description": "List all transactions for the specified budget within the start and end date.",
                "tags": [
                    "Finance Management.Budgets",
                    "ENTERPRISE"
                ],
                "summary": "Get budget transactions",
                "operationId": "getBudgetTransactions"
            }
        },
        "/api/v1/calendar/periods": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "calendar:read"
                        ]
                    }
                ],
                "description": "Get a list of detailed periods from a given start period to an end period. Will always return one of the monthly resolutions.",
                "tags": [
                    "General.Calendar",
                    "ENTERPRISE"
                ],
                "summary": "Query Period details",
                "operationId": "listPeriods"
            }
        },
        "/api/v1/calendar/periods/{period}": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "calendar:read"
                        ]
                    }
                ],
                "description": "Get details for the supplied period. Will always return one of the monthly resolutions.",
                "tags": [
                    "General.Calendar",
                    "ENTERPRISE"
                ],
                "summary": "Get period details",
                "operationId": "getPeriod"
            }
        },
        "/api/v1/categories": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "user:read"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "user:read"
                        ]
                    }
                ],
                "description": "\u003cb\u003eThe \u003ci\u003euser:read\u003c/i\u003e scope is necessary for authenticated requests.\u003c/b\u003e\n\nReturns all categories corresponding to a specified locale. The locale is determined based on the authenticated user. If there's no authenticated user, the locale will be based on the query parameter. In the absence of both an authenticated user and a query parameter, a default locale will be used. Please note that the category IDs are returned as [...]",
                "tags": [
                    "General.Category"
                ],
                "summary": "List categories",
                "operationId": "listCategories"
            }
        },
        "/api/v1/credentials": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:write"
                        ]
                    }
                ],
                "description": "Creates the Credentials for the user. The create request will trigger a refresh towards the provider.",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE"
                ],
                "summary": "Create credentials",
                "operationId": "create"
            }
        },
        "/api/v1/credentials/list": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:read"
                        ]
                    }
                ],
                "description": "List all credentials for the user.",
                "tags": [
                    "Connectivity v1.Credentials"
                ],
                "summary": "List credentials",
                "operationId": "getCredentialsList"
            }
        },
        "/api/v1/credentials/third-party/callback/relayed": {
            "post": {
                "description": "Send url-decoded callback information from an ASPSP. This endpoint will return the registered redirect uri as response.",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE"
                ],
                "summary": "Third-party callback with redirect",
                "operationId": "thirdPartyCallbackRelayedPost"
            }
        },
        "/api/v1/credentials/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:read"
                        ]
                    }
                ],
                "description": "Gets credentials by ID.",
                "tags": [
                    "Connectivity v1.Credentials"
                ],
                "summary": "Get credentials",
                "operationId": "get"
            },
            "put": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:write"
                        ]
                    }
                ],
                "description": "Modify the specified credentials. The request will trigger a refresh towards the provider.",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE"
                ],
                "summary": "Modify credentials",
                "operationId": "update"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:write"
                        ]
                    }
                ],
                "description": "Deletes the given credentials. The deletion is partly done asynchronously.",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE"
                ],
                "summary": "Delete credentials",
                "operationId": "delete"
            }
        },
        "/api/v1/credentials/{id}/accounts-selection": {},
        "/api/v1/credentials/{id}/authenticate": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:refresh"
                        ]
                    }
                ],
                "description": "Triggers a full authentication flow to renew refresh tokens with ASPSPs. This endpoint only triggers authentication, thus a full credentials refresh will not be executed.",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE"
                ],
                "summary": "Manual authenticate of credentials",
                "operationId": "manualAuthentication"
            }
        },
        "/api/v1/credentials/{id}/qr": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:read"
                        ]
                    }
                ],
                "description": "QR code for authentication flows such as Mobile BankID as base64 encoded PNG. Includes `data:image/png;base64,`.",
                "tags": [
                    "Connectivity v1.Credentials"
                ],
                "summary": "Get QR code",
                "operationId": "qrAsBase64"
            }
        },
        "/api/v1/credentials/{id}/refresh": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:refresh"
                        ]
                    }
                ],
                "description": "Refreshes the specified credentials. Please note that there can be only one on-demand refresh ongoing for a credential at a time,  any other attempts will be rejected. ",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE",
                    "REGION.US"
                ],
                "summary": "Refresh credentials",
                "operationId": "refresh"
            }
        },
        "/api/v1/credentials/{id}/supplemental-information": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "credentials:refresh"
                        ]
                    }
                ],
                "description": "Adds supplemental information to an authentication.",
                "tags": [
                    "Connectivity v1.Credentials",
                    "ENTERPRISE"
                ],
                "summary": "Add Supplemental Information",
                "operationId": "supplemental"
            }
        },
        "/api/v1/credentials/{id}:select-accounts": {},
        "/api/v1/identities": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "identity:read"
                        ]
                    }
                ],
                "description": "Lists the available identity data from each provider for a user.",
                "tags": [
                    "Data v1.Identity"
                ],
                "summary": "List identity data",
                "operationId": "listIdentityData"
            }
        },
        "/api/v1/insights": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "insights:read"
                        ]
                    }
                ],
                "description": "Lists all insights for the user. Listing insights will automatically apply any title and description overrides [configured using the Tink Console](https://docs.tink.com/resources/money-manager/money-manager-api/configure-actionable-insights). Trying to list insights with a [user locale](https://docs.tink.com/api#general/user/the-user-model/userprofile) that does not yet have a insight configuration will result in the insights being filtered out and not returned. T[...]",
                "tags": [
                    "Finance Management.Actionable Insight",
                    "ENTERPRISE"
                ],
                "summary": "List insights",
                "operationId": "list"
            }
        },
        "/api/v1/insights/action": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "insights:write"
                        ]
                    }
                ],
                "description": "Report a user action on an insight and move the insight to an archived state.",
                "tags": [
                    "Finance Management.Actionable Insight",
                    "ENTERPRISE"
                ],
                "summary": "Take action on an insight",
                "operationId": "selectInsightAction"
            }
        },
        "/api/v1/insights/archived": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "insights:read"
                        ]
                    }
                ],
                "description": "Lists all archived insights for the user. An insight is archived when a user takes action on it.",
                "tags": [
                    "Finance Management.Actionable Insight",
                    "ENTERPRISE"
                ],
                "summary": "List archived insights",
                "operationId": "listArchivedInsights"
            }
        },
        "/api/v1/insights/{id}/archive": {
            "put": {
                "security": [
                    {
                        "OAuth2User": [
                            "insights:write"
                        ]
                    }
                ],
                "description": "Move an active insight to an archived state. (DEPRECATED) should use \"POST /api/v1/insights/action\" instead.",
                "tags": [
                    "Finance Management.Actionable Insight",
                    "ENTERPRISE"
                ],
                "summary": "Archive an insight",
                "operationId": "archiveInsight",
                "deprecated": true
            }
        },
        "/api/v1/investments": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "investments:read"
                        ]
                    }
                ],
                "description": "Returns an object with a list of the authenticated user's portfolios and corresponding financial instruments.",
                "tags": [
                    "Data v1.Investment"
                ],
                "summary": "List investments",
                "operationId": "getInvestments",
                "deprecated": true
            }
        },
        "/api/v1/loans": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "accounts:read"
                        ]
                    }
                ],
                "description": "Get all the loans for a user.",
                "tags": [
                    "Data v1.Loan"
                ],
                "summary": "Get loans",
                "operationId": "getLoans",
                "deprecated": true
            }
        },
        "/api/v1/notifications/query": {
            "post": {
                "description": "Queries notifications",
                "tags": [
                    "Finance Management.Notification",
                    "ENTERPRISE"
                ],
                "summary": "Query notifications",
                "operationId": "queryNotifications",
                "deprecated": true
            }
        },
        "/api/v1/notifications/{id}/read": {
            "post": {
                "description": "Marks a notification as read",
                "tags": [
                    "Finance Management.Notification",
                    "ENTERPRISE"
                ],
                "summary": "Mark a notification as read",
                "operationId": "read",
                "deprecated": true
            }
        },
        "/api/v1/notifications/{id}/received": {
            "post": {
                "description": "Marks a notification as received (only to be used for acknowledging encrypted notifications)",
                "tags": [
                    "Finance Management.Notification",
                    "ENTERPRISE"
                ],
                "summary": "Mark a notification as received",
                "operationId": "received",
                "deprecated": true
            }
        },
        "/api/v1/oauth/authorization-grant": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "authorization:grant"
                        ]
                    }
                ],
                "description": "Creates a scoped authorization code for a user.",
                "tags": [
                    "General.OAuth",
                    "ENTERPRISE",
                    "REGION.US"
                ],
                "summary": "Create authorization",
                "operationId": "authorizationGrant"
            }
        },
        "/api/v1/oauth/authorization-grant/delegate": {
            "post": {
                "security": [
                  {
                    "Bearer": []
                  }
                ],
                "description": "Creates a delegated scoped authorization code for a user. The difference between this and `authorization-grant` is that this endpoint allows the client to specify an actor client that is allowed to use the authorization code. This is useful when a client wants to delegate access to another client.",
                "tags": [
                    "General.OAuth",
                    "ENTERPRISE",
                    "REGION.US"
                ],
                "summary": "Create delegated authorization",
                "operationId": "authorizationDelegate"
            }
        },
        "/api/v1/oauth/revoke-all": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "authorization:revoke"
                        ]
                    }
                ],
                "description": "Revokes all access tokens for a user.",
                "tags": [
                    "General.OAuth",
                    "ENTERPRISE"
                ],
                "summary": "Revoke all tokens",
                "operationId": "revokeAll"
            }
        },
        "/api/v1/oauth/token": {
            "post": {
                "description": "Access tokens are used to access API resources.",
                "tags": [
                    "General.OAuth",
                    "REGION.US"
                ],
                "summary": "Get access token",
                "operationId": "token"
            }
        },
        "/api/v1/payments/providers/{name}/payment-conditions": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "payment:read"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "payment:read"
                        ]
                    }
                ],
                "description": "Returns a `list of payment conditions` for a provider. A `payment condition` is an evaluation that the provider will have to pass for a payment to be successful. The `payment condition` is a combination of a `Rule`, `Operator` and a `Value` to form an evaluation condition that the data sent to the bank must fulfill. These conditions will apply when creating a payment request with Tink Link. Read more about payment conditions in our [guide](https://docs.tink.com/re[...]",
                "tags": [
                    "Connectivity v1.Provider",
                    "BETA"
                ],
                "summary": "Get payment conditions for a provider",
                "operationId": "getPaymentConditions"
            }
        },
        "/api/v1/payments/requests": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "payment:write"
                        ]
                    }
                ],
                "description": "Create a payment request with the given values. Returns an id which can be used with Tink Link to create a full payment journey for an end-user.",
                "tags": [
                    "Payment.Payment Request"
                ],
                "summary": "Create payment request",
                "operationId": "createPaymentUsingPOST"
            }
        },
        "/api/v1/payments/requests/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "payment:read"
                        ]
                    }
                ],
                "description": "Returns the payment request data of the given id.",
                "tags": [
                    "Payment.Payment Request"
                ],
                "summary": "Get payment request",
                "operationId": "getPaymentUsingGET"
            }
        },
        "/api/v1/payments/requests/{id}/transfers": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "payment:read"
                        ]
                    }
                ],
                "description": "Gets a list of bank transfers for a given payment request id including transfer's latest status. Payment Requests that have no transfers will return with an empty list.",
                "tags": [
                    "Payment.Payment Request"
                ],
                "summary": "Get transfers for payment request",
                "operationId": "getPaymentRequestTransfersUsingGET"
            }
        },
        "/api/v1/payments/{paymentId}/cancellation": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "payment:read"
                        ]
                    }
                ],
                "description": "Returns the cancellation data for a given payment.",
                "tags": [
                    "BETA",
                    "Payment.Cancellation"
                ],
                "summary": "Get cancellation data",
                "operationId": "getCancellationUsingGET"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "payment:write"
                        ]
                    }
                ],
                "description": "Creates the cancellation resource and initializes the cancellation for a given payment.",
                "tags": [
                    "BETA",
                    "Payment.Cancellation"
                ],
                "summary": "Begin cancellation",
                "operationId": "beginCancellationUsingPOST"
            }
        },
        "/api/v1/provider-authentication-options-for-market/{market}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "providers:read"
                        ]
                    }
                ],
                "description": "Retrieves a list of providers with its authentication options for given market",
                "tags": [
                    "Connectivity v1.Provider",
                    "BETA"
                ],
                "summary": "List authentication options for given market",
                "operationId": "ExternalAuthenticationConfigurationService_ListProvidersAuthenticationOptions"
            }
        },
        "/api/v1/provider-authentication-options/{providerName}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "providers:read"
                        ]
                    }
                ],
                "description": "Retrieves the available authentication options for a provider if it has more than one available.",
                "tags": [
                    "Connectivity v1.Provider",
                    "BETA"
                ],
                "summary": "Get the authentication options for a given provider",
                "operationId": "ExternalAuthenticationConfigurationService_GetAuthenticationOptions"
            }
        },
        "/api/v1/provider-consents": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "provider-consents:read"
                        ]
                    }
                ],
                "description": "List all provider consents for the user",
                "tags": [
                    "Connectivity v1.Provider Consent",
                    "REGION.US"
                ],
                "summary": "List Provider Consents",
                "operationId": "list"
            }
        },
        "/api/v1/provider-consents:extend": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "provider-consents:write"
                        ]
                    }
                ],
                "description": "Extend a consent that is eligible for reconfirmation (sessionExtendable attribute).",
                "tags": [
                    "Connectivity v1.Provider Consent",
                    "BETA",
                    "REGION.US"
                ],
                "summary": "Extend a consent",
                "operationId": "extend"
            }
        },
        "/api/v1/provider-identifiers": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "providers:read"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "providers:read"
                        ]
                    }
                ],
                "description": "Lists identifiers used to identify a financial institution.",
                "tags": [
                    "Connectivity v1.Provider"
                ],
                "summary": "List provider identifiers",
                "operationId": "list"
            }
        },
        "/api/v1/providers": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "credentials:read"
                        ]
                    }
                ],
                "description": "Lists all providers available for a authenticated user.",
                "tags": [
                    "Connectivity v1.Provider"
                ],
                "summary": "List providers",
                "operationId": "list"
            }
        },
        "/api/v1/providers/markets": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "providers:read"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "providers:read"
                        ]
                    }
                ],
                "description": "Lists all markets where there are providers available.",
                "tags": [
                    "Connectivity v1.Provider"
                ],
                "summary": "List markets",
                "operationId": "listMarkets"
            }
        },
        "/api/v1/providers/{market}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "providers:read"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "providers:read"
                        ]
                    }
                ],
                "description": "Lists all providers on a specified market. Your authentication affects the list of providers you get: When authenticated, the result will only contain providers available for that user. When unauthenticated and without passing The OAuth2 Client ID header, you get all providers made available for the entire environment. If you are unauthenticated but you include The OAuth2 Client ID header, you will get providers available for the app with the given client id.",
                "tags": [
                    "Connectivity v1.Provider"
                ],
                "summary": "List providers for a market",
                "operationId": "listByMarket"
            }
        },
        "/api/v1/reports-generation-jobs/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "reports-generation-jobs:readonly"
                        ]
                    }
                ],
                "description": "Fetch reports generation job",
                "tags": [
                    "BETA",
                    "General.Reports Generation Jobs"
                ],
                "summary": "Fetch reports generation job",
                "operationId": "get"
            }
        },
        "/api/v1/savings-goals": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "description": "List the user's Savings Goals.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "List Savings Goals",
                "operationId": "listSavingsGoals"
            },
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "Create a new Savings Goal.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Create Savings Goal",
                "operationId": "create"
            }
        },
        "/api/v1/savings-goals/accounts/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "description": "Get Account by ID from a Savings Goals domain.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Get Account",
                "operationId": "getAccount"
            }
        },
        "/api/v1/savings-goals/accounts/{id}/allocations": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "List allocations by Account",
                "operationId": "listAllocationsByAccount"
            }
        },
        "/api/v1/savings-goals/allocations/fund:reallocate": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "ReAllocate amount from a Savings Goal to another Savings Goal.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "ReAllocate amount",
                "operationId": "reallocateAmount"
            }
        },
        "/api/v1/savings-goals/categories": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "description": "List all available categories.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "List categories",
                "operationId": "listCategories"
            }
        },
        "/api/v1/savings-goals/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "description": "Get Savings Goal by id.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Get Savings Goal",
                "operationId": "getSavingsGoal"
            },
            "patch": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "Update a Savings Goal.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Update Savings Goal",
                "operationId": "updateSavingsGoal"
            }
        },
        "/api/v1/savings-goals/{id}/allocations": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "description": "List allocations by Savings Goal.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "List allocations",
                "operationId": "listAllocations"
            }
        },
        "/api/v1/savings-goals/{id}/allocations/fund:deposit": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "Deposit amount to a Savings Goal. If this is the first deposit to this Savings Goal the status will transition from \u003ccode\u003eCREATED\u003c/code\u003e to \u003ccode\u003eIN_PROGRESS\u003c/code\u003e.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Deposit to Savings Goal",
                "operationId": "depositAllocation"
            }
        },
        "/api/v1/savings-goals/{id}/allocations/fund:withdraw": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "Withdraw amount from a Savings Goal.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Withdraw from Savings Goal",
                "operationId": "withdraw"
            }
        },
        "/api/v1/savings-goals/{id}/period_progress": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:read"
                        ]
                    }
                ],
                "description": "Get a list of periodProgresses, based on Users \u003ccode\u003eperiodMode\u003c/code\u003e between the Savings Goal \u003ccode\u003ecreateTime\u003c/code\u003e and \u003ccode\u003etargetDate\u003c/code\u003e.\u003cbr /\u003eIf no targetDate is set on the Savings Goal, it will return PeriodProgresses between createTime and the current date",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "List periods progress",
                "operationId": "listPeriodsProgress"
            }
        },
        "/api/v1/savings-goals/{id}:archive": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "Archive a Savings Goal.\u003cbr /\u003eAll funds will be withdrawn from the Savings Goal and \u003ccode\u003estatus\u003c/code\u003e changed to \u003ccode\u003eARCHIVED\u003c/code\u003e.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Archive Savings Goal",
                "operationId": "archive"
            }
        },
        "/api/v1/savings-goals/{id}:complete": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "savings-goals:write"
                        ]
                    }
                ],
                "description": "Mark a Savings Goal as Completed\u003cbr /\u003eNo more allocations can be made from or to this goal.",
                "tags": [
                    "Finance Management.Savings Goals",
                    "ENTERPRISE"
                ],
                "summary": "Complete Savings Goal",
                "operationId": "complete"
            }
        },
        "/api/v1/search": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Queries transactions based on multiple parameters and returns a response containing transactions and their corresponding statistics matching the query. The query contains both fixed parameters and parameters parsed from the free text `queryString`. All the commands below are typically applied per word in the query and if multiple commands are found, they are concatenated with an `AND` operation (`OR` does not exist).\n\n### Query string commands\n\nType |  Descrip[...]",
                "tags": [
                    "Data v1.Search"
                ],
                "summary": "Query transactions",
                "operationId": "searchQuery"
            }
        },
        "/api/v1/statistics/query": {
            "post": {
                "security": [
                    {
                        "OAuth2": [
                            "statistics:read"
                        ]
                    }
                ],
                "description": "By querying the statistics endpoint, an API customer can select the specific types of data to access. The statistics query should be posted in the request body and you can specify any of the properties available to filter the result set. Defining multiple properties will yield an `AND` operation, and specifying multiple values of a property will yield an `OR` operation.\n\nTransfers and upcoming transactions are always excluded from statistics calculations.\n\nAdd[...]",
                "tags": [
                    "Finance Management.Statistic",
                    "ENTERPRISE"
                ],
                "summary": "Query statistics",
                "operationId": "query"
            }
        },
        "/api/v1/transactions": {
            "put": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:write"
                        ]
                    }
                ],
                "description": "Updates mutable properties of a list of transactions. The following properties are possible to update: amount, categoryId, date, description and notes. Other properties (immutable) and empty fields are ignored. Date is only updated if there is 1 day difference from existing transaction's date. The amount is only updated if there is a difference ≥ 0.001.",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Update a list of transactions",
                "operationId": "updateTransactions"
            }
        },
        "/api/v1/transactions/categorize-multiple": {
            "put": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:categorize"
                        ]
                    }
                ],
                "description": "Changes category of the supplied list of transactions to the supplied category",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Change category of transactions",
                "operationId": "categorize"
            }
        },
        "/api/v1/transactions/suggest": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Returns an object holding clusters of transactions to be categorized and possible categorization level improvement",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Get categorization clusters",
                "operationId": "suggest",
                "deprecated": true
            }
        },
        "/api/v1/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Returns a transaction matching the requested id",
                "tags": [
                    "Data v1.Transaction"
                ],
                "summary": "Get one transaction",
                "operationId": "getTransaction"
            },
            "put": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:write"
                        ]
                    }
                ],
                "description": "Updates mutable properties of a list of transactions. The following properties are possible to update: amount, categoryId, date, description and notes. Other properties (immutable) and empty fields are ignored. Date is only updated if there is 1 day difference from existing transaction's date. The amount is only updated if there is a difference ≥ 0.001.",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Update a transaction",
                "operationId": "updateTransaction"
            }
        },
        "/api/v1/transactions/{id}/link/suggest": {
            "get": {
                "description": "(DEPRECATED) Returns suggestions for potential counterpart expenses for a reimbursement.",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Get counterpart suggestions",
                "operationId": "linkSuggest",
                "deprecated": true
            }
        },
        "/api/v1/transactions/{id}/link/{counterpartTransactionId}": {
            "post": {
                "description": "(DEPRECATED) Link two transactions, creating a transaction part for each transaction and netting out the amounts. The transactions are required to have different signs (i.e. one income and one expense). If the first transaction is -300 and the counterpart is 100, the common disposable amount is 100 and result of that is a dispensable amount of -200.",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Link transactions",
                "operationId": "link",
                "deprecated": true
            }
        },
        "/api/v1/transactions/{id}/part/{partId}": {
            "put": {
                "description": "(DEPRECATED) Updates an transaction part amount and it's counterpart amount.",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Update transaction Link",
                "operationId": "updateLink",
                "deprecated": true
            },
            "delete": {
                "description": "(DEPRECATED) If the part is linked to another transaction, the bilateral link is removed as well (i.e. the counterpart will be removed too, if found).",
                "tags": [
                    "Data v1.Transaction",
                    "ENTERPRISE"
                ],
                "summary": "Delete transaction part",
                "operationId": "deletePart",
                "deprecated": true
            }
        },
        "/api/v1/transactions/{id}/similar": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Returns an object holding a list of transactions similar to the supplied transaction based on description and a list of statistics summarizing these transactions",
                "tags": [
                    "Data v1.Transaction"
                ],
                "summary": "Get similar transactions",
                "operationId": "similar"
            }
        },
        "/api/v1/user": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "user:read"
                        ]
                    }
                ],
                "description": "Returns the authenticated user.",
                "tags": [
                    "General.User"
                ],
                "summary": "Get user",
                "operationId": "getUser"
            },
            "patch": {
                "security": [
                    {
                        "OAuth2User": [
                            "user:write"
                        ]
                    }
                ],
                "description": "Updates the modifiable fields of a user. Refer to the [User model](#general/user/the-user-model) for which fields are modifiable. The `id` of the user must also be given, and must match the ID of the authenticated user access token.",
                "tags": [
                    "General.User",
                    "ENTERPRISE"
                ],
                "summary": "Update user",
                "operationId": "updateUser"
            }
        },
        "/api/v1/user/create": {
            "post": {
                "security": [
                  {
                    "Bearer": []
                  }
                ],
                "description": "Creates a user and its user profile and returns the ID of the created user.",
                "tags": [
                    "General.User",
                    "ENTERPRISE",
                    "REGION.US"
                ],
                "summary": "Create user",
                "operationId": "createUser"
            }
        },
        "/api/v1/user/delete": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "user:delete"
                        ]
                    }
                ],
                "description": "Completely deletes the currently authenticated user and its data.",
                "tags": [
                    "General.User",
                    "ENTERPRISE",
                    "REGION.US"
                ],
                "summary": "Delete user",
                "operationId": "delete"
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "user:read"
                        ]
                    }
                ],
                "description": "Returns the authenticated user's profile.",
                "tags": [
                    "General.User"
                ],
                "summary": "Get user profile",
                "operationId": "getProfile"
            },
            "put": {
                "security": [
                    {
                        "OAuth2User": [
                            "user:write"
                        ]
                    }
                ],
                "description": "Updates the modifiable fields of a user's profile. Refer to the [UserProfile model](#general/user/the-user-model/userprofile) for which fields are modifiable.",
                "tags": [
                    "General.User",
                    "ENTERPRISE"
                ],
                "summary": "Update user profile",
                "operationId": "updateProfile"
            }
        },
        "/connectivity/v2/authorizations:relay-callback": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    }
                ],
                "description": "Send url-decoded callback information from an ASPSP.",
                "tags": [
                    "Connectivity v2.Authorization",
                    "BETA"
                ],
                "summary": "Relayed callback for redirect flows",
                "operationId": "postCallbackRelayed"
            }
        },
        "/connectivity/v2/consent-templates/{providerId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents:readonly"
                        ]
                    }
                ],
                "description": "Request a JSON schema template that's used to create a mandate.",
                "tags": [
                    "Connectivity v2.Consent Templates",
                    "BETA"
                ],
                "summary": "Get consent template",
                "operationId": "getConsentFinancialServiceParametersTemplates"
            }
        },
        "/connectivity/v2/consents": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "consents:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents:readonly"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Consent",
                    "BETA"
                ],
                "summary": "List consents",
                "operationId": "getConsents"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Consent",
                    "BETA"
                ],
                "summary": "Create a new consent",
                "operationId": "createConsent"
            }
        },
        "/connectivity/v2/consents/{consentId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "consents:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents:readonly"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Consent",
                    "BETA"
                ],
                "summary": "Read a consent",
                "operationId": "getConsent"
            }
        },
        "/connectivity/v2/consents/{consentId}/authorizations": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "consents:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents:readonly"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Authorization",
                    "BETA"
                ],
                "summary": "List authorizations",
                "operationId": "getAuthorizations"
            },
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "consents"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Authorization",
                    "BETA"
                ],
                "summary": "Start authorization for a consent",
                "operationId": "createAuthorization"
            }
        },
        "/connectivity/v2/consents/{consentId}/authorizations/{authorizationId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "consents:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "consents:readonly"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Authorization",
                    "BETA"
                ],
                "summary": "Read authorization",
                "operationId": "getAuthorization"
            }
        },
        "/connectivity/v2/consents/{consentId}:revoke": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "consents"
                        ]
                    }
                ],
                "tags": [
                    "Connectivity v2.Consent",
                    "BETA"
                ],
                "summary": "Revoke a consent",
                "operationId": "revokeConsent"
            }
        },
        "/connector/users/{externalUserId}/accounts": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "accounts:write"
                        ]
                    }
                ],
                "description": "Takes a list of accounts and the corresponding user ID.",
                "tags": [
                    "ENTERPRISE",
                    "Connector.Account",
                    "MULTI_TENANT"
                ],
                "summary": "Ingest accounts",
                "operationId": "createAccounts"
            }
        },
        "/connector/users/{externalUserId}/accounts/{externalAccountId}": {
            "put": {
                "security": [
                    {
                        "OAuth2Client": [
                            "accounts:write"
                        ]
                    }
                ],
                "description": "Accepts an object of properties to be updated.",
                "tags": [
                    "ENTERPRISE",
                    "Connector.Account",
                    "MULTI_TENANT"
                ],
                "summary": "Update account",
                "operationId": "updateAccount"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Client": [
                            "accounts:write"
                        ]
                    }
                ],
                "description": "Deletes the account with the given account ID.",
                "tags": [
                    "ENTERPRISE",
                    "Connector.Account",
                    "MULTI_TENANT"
                ],
                "summary": "Delete account",
                "operationId": "deleteAccount"
            }
        },
        "/connector/users/{externalUserId}/transactions": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "transactions:write"
                        ]
                    }
                ],
                "description": "Takes historical or real time transactions together with an account.",
                "tags": [
                    "ENTERPRISE",
                    "Connector.Transaction",
                    "MULTI_TENANT"
                ],
                "summary": "Ingest transactions",
                "operationId": "ingestTransactions"
            }
        },
        "/connector/users/{externalUserId}/transactions/delete": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "transactions:write"
                        ]
                    }
                ],
                "description": "Removes transactions. When deleting transactions, it's only the externalId of each transaction that is necessary.",
                "tags": [
                    "ENTERPRISE",
                    "Connector.Transaction",
                    "MULTI_TENANT"
                ],
                "summary": "Delete transactions",
                "operationId": "deleteTransactions"
            }
        },
        "/connector/users/{externalUserId}/transactions/{externalTransactionId}": {
            "put": {
                "security": [
                    {
                        "OAuth2Client": [
                            "transactions:write"
                        ]
                    }
                ],
                "description": "Updates a single transaction related to an account.",
                "tags": [
                    "ENTERPRISE",
                    "Connector.Transaction",
                    "MULTI_TENANT"
                ],
                "summary": "Update transaction",
                "operationId": "updateTransactions"
            }
        },
        "/data/v1/business-account-verification-reports/{id}": {
            "get": {
                "security": [
                  {
                    "Bearer": []
                  }
                ],
                "description": "Returns a business account verification response",
                "tags": [
                    "Data v1.Business Account Verification"
                ],
                "summary": "Get Business Account Verification Report",
                "operationId": "getBusinessAccountVerification"
            }
        },
        "/data/v2/accounts": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "accounts:read"
                        ]
                    }
                ],
                "description": "Returns a list of accounts for a user.",
                "tags": [
                    "Data v2.Account",
                    "REGION.US"
                ],
                "summary": "List Accounts",
                "operationId": "AccountsService_ListAccounts"
            }
        },
        "/data/v2/accounts/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "accounts:read"
                        ]
                    }
                ],
                "description": "Returns an account for given user and id.",
                "tags": [
                    "Data v2.Account",
                    "REGION.US"
                ],
                "summary": "Get Account",
                "operationId": "AccountsService_GetAccount"
            }
        },
        "/data/v2/accounts/{id}/balances": {
            "get": {
                "security": [
                  {
                    "Bearer": []
                  }
                ],
                "description": "Signage on balances:\nThe balance amount signage is either positive or negative - \n1. A balance that is `positive` indicates there are funds available to be spent.\n2. A balance that is `negative` indicates that the user owes funds to the financial institution.\nThe above is true for both depository accounts and credit accounts.",
                "tags": [
                    "Data v2.Account",
                    "BETA",
                    "REGION.US"
                ],
                "summary": "Get Account Balances",
                "operationId": "getBalances"
            }
        },
        "/data/v2/accounts/{id}/parties": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "accounts:read",
                            "accounts.parties:readonly"
                        ]
                    }
                ],
                "description": "Returns accounts parties",
                "tags": [
                    "Data v2.Account"
                ],
                "summary": "Get Account Parties",
                "operationId": "getParties"
            }
        },
        "/data/v2/identities": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "identities:readonly"
                        ]
                    }
                ],
                "description": "Returns identities for user",
                "tags": [
                    "Data v2.Identity",
                    "BETA"
                ],
                "summary": "List Identities",
                "operationId": "getIdentities"
            }
        },
        "/data/v2/investment-accounts": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "investment-accounts:readonly"
                        ]
                    }
                ],
                "description": "Returns a list of investment accounts for a user.",
                "tags": [
                    "Data v2.Investment"
                ],
                "summary": "List Investment Accounts",
                "operationId": "getInvestmentAccountsByUserId"
            }
        },
        "/data/v2/investment-accounts/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "investment-accounts:readonly"
                        ]
                    }
                ],
                "description": "Returns an investment account for a given investment account id",
                "tags": [
                    "Data v2.Investment"
                ],
                "summary": "Get Investment Account",
                "operationId": "getInvestmentAccountById"
            }
        },
        "/data/v2/investment-accounts/{id}/holdings": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "investment-accounts:readonly"
                        ]
                    }
                ],
                "description": "Returns a list of holdings for an investment account.",
                "tags": [
                    "Data v2.Investment"
                ],
                "summary": "List Holdings",
                "operationId": "getHoldings"
            }
        },
        "/data/v2/loan-accounts": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "loan-accounts:readonly"
                        ]
                    }
                ],
                "description": "Returns a list of loan accounts for a user.",
                "tags": [
                    "Data v2.Loan"
                ],
                "summary": "List Loan Accounts",
                "operationId": "getLoanAccounts"
            }
        },
        "/data/v2/loan-accounts/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "loan-accounts:readonly"
                        ]
                    }
                ],
                "description": "Returns a loan account for a given loan account id.",
                "tags": [
                    "Data v2.Loan"
                ],
                "summary": "Get Loan Account",
                "operationId": "getLoanAccountById"
            }
        },
        "/data/v2/transaction-reports/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "transaction-reports:readonly"
                        ]
                    }
                ],
                "description": "Reports are available for retrieval up to 1h after generation and permanently deleted after 24h.",
                "tags": [
                    "Data v2.Transaction Report"
                ],
                "summary": "Get Transaction Report",
                "operationId": "ReportsService_GetReport"
            }
        },
        "/data/v2/transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Returns a list of transactions for a user.",
                "tags": [
                    "Data v2.Transaction",
                    "REGION.US"
                ],
                "summary": "List Transactions",
                "operationId": "TransactionsService_ListTransactions"
            }
        },
        "/data/v2/transactions/{id}": {},
        "/enrichment/v1/brand-identification/brands/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.merchant"
                        ]
                    }
                ],
                "description": "Fetches a brand by its ID. The ID is a UUID.\n\nThe response will include the brand's name, logo and contact information.\n",
                "tags": [
                    "Enrichment.Merchant Information.Brand"
                ],
                "summary": "Get Brand By ID",
                "operationId": "getBrandById"
            }
        },
        "/enrichment/v1/brand-identification/merchants/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.merchant"
                        ]
                    }
                ],
                "description": "Fetches a merchant by its ID. The ID is a UUID.\n\nThe response will include the merchant's name, logo, location and contact information.\n",
                "tags": [
                    "Enrichment.Merchant Information.Merchant"
                ],
                "summary": "Get Merchant By ID",
                "operationId": "getMerchantById"
            }
        },
        "/enrichment/v1/categories": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "enrichment.transactions:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "enrichment.transactions"
                        ]
                    }
                ],
                "description": "List all categories for a locale.",
                "tags": [
                    "Enrichment.Category",
                    "REGION.US"
                ],
                "summary": "List All Categories",
                "operationId": "listCategories"
            }
        },
        "/enrichment/v1/predicted-recurring-transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "transactions.recurring:read"
                        ]
                    }
                ],
                "description": "List predicted recurring transactions for a user. All fields are optional, which means that setting none of the fields will return 30 days of predictions for all of a user's active groups.\n\nTo forecast recurring transactions for 30 days ahead, the model checks if an existing recurring transactions group is active. If that is the case, the model will look at the last date for when the transactions occurred and calculate that together with the found periodicity fo[...]",
                "tags": [
                    "Enrichment.Recurring Transactions",
                    "REGION.US"
                ],
                "summary": "List Predicted Recurring Transactions",
                "operationId": "listPRTXs"
            }
        },
        "/enrichment/v1/recurring-transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "transactions.recurring:read"
                        ]
                    }
                ],
                "description": "List all recurring transactions for a user.\n",
                "tags": [
                    "Enrichment.Recurring Transactions",
                    "REGION.US"
                ],
                "summary": "List Recurring Transactions",
                "operationId": "listRTX"
            }
        },
        "/enrichment/v1/recurring-transactions-groups": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "transactions.recurring:read"
                        ]
                    }
                ],
                "description": "List all recurring transactions groups for a user.",
                "tags": [
                    "Enrichment.Recurring Transactions",
                    "REGION.US"
                ],
                "summary": "List Recurring Transactions Groups",
                "operationId": "listRTXGroup"
            }
        },
        "/enrichment/v1/recurring-transactions-groups/{groupId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "transactions.recurring:read"
                        ]
                    }
                ],
                "description": "Get a single recurring transactions group for a user.",
                "tags": [
                    "Enrichment.Recurring Transactions",
                    "REGION.US"
                ],
                "summary": "Get a Recurring Transactions Group",
                "operationId": "getRTXGroup"
            }
        },
        "/enrichment/v1/sustainability/accounts/profiling": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability"
                        ]
                    }
                ],
                "description": "Profiling questions are answered using this endpoint. Answer ID refers to the ID in the SELECTABLE or INPUT array.\n",
                "tags": [
                    "Enrichment.Sustainability.Account Profiling"
                ],
                "summary": "Answer Profiling Questions",
                "operationId": "profiling"
            }
        },
        "/enrichment/v1/sustainability/accounts/{accountId}/insights": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability"
                        ]
                    }
                ],
                "description": "Retrieves a random account specific insight. The insights returned will be affected depending  on what the end user has answered in it's account profiling.The language of the insights depends on the language parameter. Default is English.\n",
                "tags": [
                    "Enrichment.Sustainability.Insights"
                ],
                "summary": "Retrieve a random account specific insight.",
                "operationId": "insights_1"
            }
        },
        "/enrichment/v1/sustainability/accounts/{accountId}/profiling": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability"
                        ]
                    }
                ],
                "description": "This returns questions to be answered by users for more precise CO2 calculations, comparisons, or insights. The questions will be in the language specified by the language parameter. It defaults to English.\n\n\u003cb\u003eThere are two types of questions:\u003c/b\u003e\n  - SELECTABLE: The user can select an answer from a list\n  - INPUT: The user is asked to give a free text answer of the specified type and according to validation\n",
                "tags": [
                    "Enrichment.Sustainability.Account Profiling"
                ],
                "summary": "Get Profiling Questions",
                "operationId": "profiling_1"
            }
        },
        "/enrichment/v1/sustainability/insights": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability"
                        ]
                    }
                ],
                "description": "Retrieves general insights, these are not affected by Your account profile. The language of the insights depends on the language parameter. Default is English.\n",
                "tags": [
                    "Enrichment.Sustainability.Insights"
                ],
                "summary": "Retrieve general insights",
                "operationId": "insights"
            }
        },
        "/enrichment/v1/sustainability/market-average": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability"
                        ]
                    }
                ],
                "description": "Retrieves the annual average CO2 footprint for the supplied market. ",
                "tags": [
                    "Enrichment.Sustainability.Market Average"
                ],
                "summary": "Retrieve market average footprints",
                "operationId": "getMarketAverage"
            }
        },
        "/enrichment/v1/sustainability/transactions/refinement": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability",
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Refinement questions are answered using this endpoint. Answer ID refers to the ID in the SELECTABLE or INPUT array.\n",
                "tags": [
                    "Enrichment.Sustainability.Transactions"
                ],
                "summary": "Answer refinement questions",
                "operationId": "refinement"
            }
        },
        "/enrichment/v1/sustainability/transactions/{transactionId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability",
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Retrieve base sustainability info for the specified transaction. The response will include the CO2 emission value, random comparison and a random insight.\n",
                "tags": [
                    "Enrichment.Sustainability.Transactions"
                ],
                "summary": "Transaction Sustainability Info",
                "operationId": "transactionSustainabilityInfo"
            }
        },
        "/enrichment/v1/sustainability/transactions/{transactionId}/comparables": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability",
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Retrieve a list of relatable comparisons corresponding to the CO2 emission value of the transaction.\n",
                "tags": [
                    "Enrichment.Sustainability.Transactions"
                ],
                "summary": "List transaction CO2 value comparison",
                "operationId": "comparables"
            }
        },
        "/enrichment/v1/sustainability/transactions/{transactionId}/refinement": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.sustainability",
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Retrieves refinement questions for the specified transaction.\n\n\u003cb\u003eThere are two types of questions:\u003c/b\u003e\n  - SELECTABLE: The user can select an answer from a list\n  - INPUT: The user is asked to give a free text answer of the specified type and according to validation\n",
                "tags": [
                    "Enrichment.Sustainability.Transactions"
                ],
                "summary": "List refinement questions for transaction",
                "operationId": "refinement_1"
            }
        },
        "/enrichment/v1/transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    }
                ],
                "description": "List all enriched transactions for a user.",
                "tags": [
                    "Enrichment.Enriched Transactions",
                    "REGION.US"
                ],
                "summary": "List Enriched Transactions",
                "operationId": "listTransactions"
            },
            "patch": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly"
                        ]
                    }
                ],
                "description": "Update one or more enriched transactions categories.",
                "tags": [
                    "Enrichment.Enriched Transactions"
                ],
                "summary": "Update Enriched Transactions",
                "operationId": "updateTransactions"
            }
        },
        "/enrichment/v1/transactions/on-demand": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "enrichment.on-demand"
                        ]
                    }
                ],
                "description": "\u003cp\u003eEnrich transactions without the need for users or accounts to be created. This endpoint does not store any data. The enrichments provided include:\u003c/p\u003e\n\u003cul\u003e\n    \u003cli\u003e\u003cstrong\u003eCategorization\u003c/strong\u003e: Tink category ID and formatted description\u003c/li\u003e\n    \u003cli\u003e\u003cstrong\u003eMerchant Information\u003c/strong\u003e: Brand and Merchant information\u003c/li\u003e\n\u003c/ul\u003e\n\u003c[...]",
                "tags": [
                    "Enrichment.As a Service"
                ],
                "summary": "Enrich transactions",
                "operationId": "enrichTransactions"
            }
        },
        "/enrichment/v1/transactions/{transactionId}:find-similar": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "enrichment.transactions:readonly",
                            "transactions:read"
                        ]
                    },
                    {
                        "OAuth2User": [
                            "enrichment.transactions",
                            "transactions:read"
                        ]
                    }
                ],
                "description": "Get up to 50 similar transactions to the specified transaction.",
                "tags": [
                    "Enrichment.Enriched Transactions",
                    "REGION.US"
                ],
                "summary": "Get Similar Transactions",
                "operationId": "getSimilarTransactions"
            }
        },
        "/events/v2/webhook-endpoints": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "webhook-endpoints"
                        ]
                    }
                ],
                "description": "Returns a list of Webhook Endpoints.",
                "tags": [
                    "Events v2.Webhook",
                    "REGION.US"
                ],
                "summary": "List Webhook Endpoints",
                "operationId": "WebhookEndpointService_ListWebhookEndpoints"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "webhook-endpoints"
                        ]
                    }
                ],
                "description": "The Events v2 Create Webhook Endpoint creates a subscription for a set of events to be delivered to a given endpoint URL. These webhooks are set to trigger whenever a subscribed event occurs for any user created for your app.\n\nPlease visit the relevant Tink product page in our [documentation](https://docs.tink.com/ \"https://docs.tink.com/\") to learn more details on how to integrate and subscribe to webhook events related to product(s) you use.\n\nDue to the un[...]",
                "tags": [
                    "Events v2.Webhook",
                    "REGION.US"
                ],
                "summary": "Create Webhook Endpoint",
                "operationId": "WebhookEndpointService_CreateWebhookEndpoint"
            }
        },
        "/events/v2/webhook-endpoints/{id}": {
            "delete": {
                "security": [
                    {
                        "OAuth2Client": [
                            "webhook-endpoints"
                        ]
                    }
                ],
                "description": "Deletes a Webhook Endpoint.",
                "tags": [
                    "Events v2.Webhook",
                    "REGION.US"
                ],
                "summary": "Delete Webhook Endpoint",
                "operationId": "WebhookEndpointService_DeleteWebhookEndpoint"
            }
        },
        "/events/v2/webhook-endpoints/{webhookEndpoint.id}": {
            "patch": {
                "security": [
                    {
                        "OAuth2Client": [
                            "webhook-endpoints"
                        ]
                    }
                ],
                "description": "Updates a Webhook Endpoint.",
                "tags": [
                    "Events v2.Webhook",
                    "REGION.US"
                ],
                "summary": "Update Webhook Endpoint",
                "operationId": "WebhookEndpointService_UpdateWebhookEndpoint"
            }
        },
        "/finance-management/v1/business-budgets": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "budgets-bfm"
                        ]
                    }
                ],
                "description": "Lists all available Business Budgets. Additionally, response can be filtered using query parameters\n\n### Active Budgets\nIn order to list only active Business Budgets, a request must be filled with both dates\n(_periodRangeGte_ and _periodRangeLte_) to *today*.\n\nExample (current day = \"2022-01-10\")\n```\n{\n    \"periodRangeGte\": \"2022-01-10\",\n    \"periodRangeLte\": \"2022-01-10\"\n}\n```",
                "tags": [
                    "Finance Management.Business Budgets",
                    "BETA"
                ],
                "summary": "List Business Budgets",
                "operationId": "BfmBudgetsService_ListBudgets"
            },
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "budgets-bfm"
                        ]
                    }
                ],
                "description": "Create Business Budget based on provided input\n\n#### Allocation Filter logic\n\nAllocation Filters are grouped into two groups:\n* _Income_ Allocation Filters\n* _Expense_ Allocation Filters\n\nDepending on a Business Budget type they can be treated differently:\n\n| Budget Type | Income Allocation Filters | Expense Allocation Filters |\n|-------------|---------------------------|----------------------------|\n| Income      | +                         | -       [...]",
                "tags": [
                    "Finance Management.Business Budgets",
                    "BETA"
                ],
                "summary": "Create Business Budget",
                "operationId": "BfmBudgetsService_CreateBudget"
            }
        },
        "/finance-management/v1/business-budgets/{budgetId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "budgets-bfm"
                        ]
                    }
                ],
                "description": "Get provided Business Budget by provided `budget_id`",
                "tags": [
                    "Finance Management.Business Budgets",
                    "BETA"
                ],
                "summary": "Get Detailed Business Budget",
                "operationId": "BfmBudgetsService_GetBudgetDetails"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2User": [
                            "budgets-bfm"
                        ]
                    }
                ],
                "description": "Delete specified Business Budget",
                "tags": [
                    "Finance Management.Business Budgets",
                    "BETA"
                ],
                "summary": "Delete Business Budget",
                "operationId": "BfmBudgetsService_DeleteBudget"
            },
            "patch": {
                "security": [
                    {
                        "OAuth2User": [
                            "budgets-bfm"
                        ]
                    }
                ],
                "description": "Update Business Budget by provided `budget_id`\n\n#### Update request limitation\n\nNot all changes are permitted with update request. If such change is needed, we recommend creating a new budget.\n\nFor recurrence properties, only changing the end date to later is allowed. In other words, it’s not allowed to:\n* change recurrence frequency (for example from Weekly to Monthly)\n* change start date of recurrence (as the Start date defines week day for budget start [...]",
                "tags": [
                    "Finance Management.Business Budgets",
                    "BETA"
                ],
                "summary": "Update Business Budget",
                "operationId": "BfmBudgetsService_UpdateBudget"
            }
        },
        "/finance-management/v1/business-budgets/{budgetId}/history": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "budgets-bfm"
                        ]
                    }
                ],
                "description": "List all historical Business Budgets (ones that already ended) and current one.\n\nReturned Business Budgets are ordered by descending start date.",
                "tags": [
                    "Finance Management.Business Budgets",
                    "BETA"
                ],
                "summary": "List Business Budget History",
                "operationId": "BfmBudgetsService_ViewBudgetHistory"
            }
        },
        "/finance-management/v1/cash-flow-summaries/{resolution}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "cash-flow"
                        ]
                    }
                ],
                "description": "Returns aggregated transactions information for specified length of time with requested period resolution.\nIf period does not contain any transactions or events it will be still generated with sums equal to zero.",
                "tags": [
                    "Finance Management.Cash flow",
                    "BETA"
                ],
                "summary": "List cash flows summaries",
                "operationId": "CashFlowService_ListCashFlowSummaries"
            }
        },
        "/finance-management/v1/cost-of-living": {},
        "/finance-management/v1/cost-of-living/{costOfLivingId}/transactions": {},
        "/finance-management/v1/financial-calendar-events": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar:readonly"
                        ]
                    }
                ],
                "description": "Perform lookup in events that start at `due_date_gte` time and end at `due_date_lte`.\nAccepted time format is ISO8601: YYYY-MM-DD.\nIt is possible to fetch data between 10 years (early and late). If time range will be longer than that no data will be returned\nand error will be thrown.\n\nPlease keep in mind, that in case of Income event (positive amount), `Action Indicator` presents different logic.\n\n### Income Action Indicator Meaning\n\nAction Indicator | Me[...]",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Lists calendar events within given timeframe",
                "operationId": "FinancialCalendarService_ListCalendarEvents"
            },
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Create a new calendar event based on provided data.\n\n### Event types\n\nType | Condition | Available Action Indicators\n---- | ----------------- | -----------------\nIncome | Positive Event Amount | `NO_REMAINING_ACTION_NEEDED` `ACTION_LATER` `NOT_COMPLETED_PAST_DUE_DATE` `COMPLETED_NOT_RECONCILED_PAST_DUE_DATE`\nExpense | Negative Event Amount | `NO_REMAINING_ACTION_NEEDED` `ACTION_LATER` `ACTION_URGENT` `ACTION_CRITICAL` `NOT_COMPLETED_PAST_DUE_DATE` `COMPLETE[...]",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Create a new calendar event",
                "operationId": "FinancialCalendarService_CreateCalendarEvent"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar:readonly"
                        ]
                    }
                ],
                "description": "Perform lookup in events to find the one with matching id.\n\nPlease keep in mind, that in case of Income event (positive amount), `Action Indicator` presents different logic.\n\n### Income Action Indicator Meaning\n\nAction Indicator | Meaning\n---- | -----------------\n`NO_REMAINING_ACTION_NEEDED` | Event reconciled and completed\n`ACTION_LATER` | Action not yet past `dueDate`\n`NOT_COMPLETED_PAST_DUE_DATE` | Event after `dueDate`, not completed and not fully re[...]",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Get event by id",
                "operationId": "FinancialCalendarService_GetCalendarEvent"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Delete event that matches given `calendar_event_id`.",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Delete event by id",
                "operationId": "FinancialCalendarService_DeleteCalendarEvent"
            },
            "patch": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Make changes to already existing event. Event specified by `calendar_event_id` will be updated with values from body.\nFor Action Indicator explanation please see Create Calendar Event endpoint.\n\n### Access Management\n\nSpecifying __accountIds__ field as an empty list is equivalent to indicating that event will\nbe accessible only by the users that had access to all accounts which were present the moment of event update.\n\nPlease keep in mind, that in case of [...]",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Update event by id",
                "operationId": "FinancialCalendarService_UpdateCalendarEvent"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/attachments": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Add an attachment to the calendar event with ID equal to `calendar_event_id`",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Add attachment",
                "operationId": "FinancialCalendarService_CreateCalendarEventAttachment"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/attachments/{attachmentId}": {
            "delete": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Remove attachment given its ID `attachment_id` from event specified by `calendar_event_id`.",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Delete attachment",
                "operationId": "FinancialCalendarService_DeleteCalendarEventAttachment"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/reconciliations": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Perform reconciliation (linking) process on event based on provided `calendar_event_id`.\nReconciliation process links target event with existing transaction defined in request body by `transaction_id`.",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Reconcile(link) event with a transaction",
                "operationId": "FinancialCalendarService_CreateCalendarEventReconciliation"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/reconciliations/details": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar:readonly"
                        ]
                    }
                ],
                "description": "Get details of reconciliations between event and transactions",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Get reconciliations(links) details",
                "operationId": "FinancialCalendarService_GetCalendarEventReconciliationDetails"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/reconciliations/suggestions": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar:readonly"
                        ]
                    }
                ],
                "description": "Get Suggested transaction ids that may be used for reconciliation of given calendar event (with `calendar_event_id`).\n\n#### Access Management\n\nThis endpoint will only list suggested _Transactions_ that are related to the _Accounts_\nrelated with Financial Calendar event.",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Get Suggested transactions",
                "operationId": "FinancialCalendarService_ListReconciliationSuggestions"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/reconciliations/{transactionId}": {
            "delete": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Delete reconciliation(link) between event and transaction.",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Delete reconciliation(link)",
                "operationId": "FinancialCalendarService_DeleteCalendarEventReconciliation"
            }
        },
        "/finance-management/v1/financial-calendar-events/{calendarEventId}/recurring-group": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar"
                        ]
                    }
                ],
                "description": "Define an event (with `calendar_event_id`) as recurring.\nEvent recurrence is compliant with RFC-5545 Recurrence Rule pattern.",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "Make an event recurring",
                "operationId": "FinancialCalendarService_CreateCalendarEventRecurringGroup"
            }
        },
        "/finance-management/v1/financial-calendar-summaries/{resolution}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "financial-calendar:readonly"
                        ]
                    }
                ],
                "description": "List events that match specified resolution. Resolution parameter `resolution` is defined as an enum.\nGlossary:\n DAILY = 1\n WEEKLY = 2\n MONTHLY = 3\n YEARLY = 4\n\n#### Access Management\n\nEvent access is defined on a per __accountId__ basis.\nAccount ids that user has access to are specified in __account_id_in__ parameter.\nEvent will be accessible only if user has access to ALL accounts related with the event.\nNot specifying __accountIds__ (or is specifyin[...]",
                "tags": [
                    "Finance Management.Financial calendar",
                    "BETA"
                ],
                "summary": "List events summaries for the given period",
                "operationId": "FinancialCalendarService_ListCalendarSummaries"
            }
        },
        "/finance-management/v1/subscriptions": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "subscriptions:read"
                        ]
                    }
                ],
                "description": "Lists all subscriptions belonging to the user. Optionally it can be filtered for specific accounts.",
                "tags": [
                    "Finance Management.Subscriptions",
                    "ENTERPRISE"
                ],
                "summary": "List user subscriptions",
                "operationId": "getSubscriptions"
            }
        },
        "/finance-management/v1/subscriptions/{subscriptionId}/transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2": [
                            "subscriptions:read"
                        ]
                    }
                ],
                "description": "Lists all transactions belonging to the subscription.",
                "tags": [
                    "Finance Management.Subscriptions",
                    "ENTERPRISE"
                ],
                "summary": "List subscription transactions",
                "operationId": "getTransactions"
            }
        },
        "/internal/connectivity/v1/balance-refresh": {},
        "/internal/predicted-recurring-transactions": {},
        "/internal/recurring-transactions": {},
        "/internal/recurring-transactions-groups": {},
        "/internal/recurring-transactions-groups/{groupId}": {},
        "/internal/refresh": {},
        "/link/v1/session": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "link-session:write"
                        ]
                    }
                ],
                "description": "You can optionally use a session to configure certain aspects of the Tink Link flow for a specific user (such as securely pre-filling information or configuring specific behaviors). A session is one-time use only and has a lifetime of 10 minutes.",
                "tags": [
                    "General.Tink Link.Session"
                ],
                "summary": "Create a session",
                "operationId": "SessionService_CreateSession"
            }
        },
        "/link/v1/session/{sessionId}": {
            "get": {
                "security": [
                    {
                        "OAuth2User": [
                            "link-session:read"
                        ]
                    }
                ],
                "tags": [
                    "SessionService"
                ],
                "operationId": "SessionService_GetSession"
            }
        },
        "/partner-integration/v1/merchants": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "merchants:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "merchants:readonly"
                        ]
                    }
                ],
                "description": "List all merchants associated with the given application.",
                "tags": [
                    "Partner Integration.Merchants",
                    "BETA"
                ],
                "summary": "List merchants",
                "operationId": "MerchantsService_ListMerchants"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "merchants"
                        ],
                        "OAuth2OrgUser": [
                            "merchants"
                        ]
                    }
                ],
                "description": "Creates a new merchant.",
                "tags": [
                    "Partner Integration.Merchants",
                    "BETA"
                ],
                "summary": "Create merchant",
                "operationId": "MerchantsService_CreateMerchant"
            }
        },
        "/partner-integration/v1/merchants/json-schema": {},
        "/partner-integration/v1/merchants/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "merchants:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "merchants:readonly"
                        ]
                    }
                ],
                "description": "Retrieve information about an existing merchant.",
                "tags": [
                    "Partner Integration.Merchants",
                    "BETA"
                ],
                "summary": "Get merchant",
                "operationId": "MerchantsService_GetMerchant"
            }
        },
        "/payment/v1/bulk-payments/{id}:initiate": {},
        "/payment/v1/mandate-payments": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "mandate-payments"
                        ]
                    }
                ],
                "description": "Creates a mandate payment, when given a valid consent id.",
                "tags": [
                    "Payment.Mandate Payment",
                    "BETA"
                ],
                "summary": "Create mandate payment",
                "operationId": "createMandatePayment"
            }
        },
        "/payment/v1/mandate-payments/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "mandate-payments:readonly"
                        ]
                    }
                ],
                "description": "Returns the mandate payment of a given mandate payment id.",
                "tags": [
                    "Payment.Mandate Payment",
                    "BETA"
                ],
                "summary": "Get mandate payment",
                "operationId": "getMandatePayment"
            }
        },
        "/payment/v1/merchants/{account.merchantId}/accounts/{account.id}": {
            "patch": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Updates the settlement account object, more specifically only the payout account object within can be updated.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Update account",
                "operationId": "SettlementAccountsService_UpdateSettlementAccount"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "List all settlement accounts for a given merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "List accounts",
                "operationId": "SettlementAccountsService_ListSettlementAccounts"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Creates a new settlement account for the merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Create account",
                "operationId": "SettlementAccountsService_CreateSettlementAccount"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Retrieves a specific settlement account for a given merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Get account",
                "operationId": "SettlementAccountsService_GetSettlementAccount"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}/refunds": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Lists the refunds for a specific settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "List refunds",
                "operationId": "SettlementAccountsService_ListSettlementAccountRefunds"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Creates a refund for the specific transaction, settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Create refund",
                "operationId": "SettlementAccountsService_CreateSettlementAccountRefund"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}/refunds/{refundId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Retrieves a specific refund for a specific settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Get refund",
                "operationId": "SettlementAccountsService_GetSettlementAccountRefund"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}/transactions": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Lists the transactions for a specific settlement account for a given merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "List transactions",
                "operationId": "SettlementAccountsService_ListSettlementAccountTransactions"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}/transactions/{transactionId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Retrieves a specific transaction for a specific settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Get transaction",
                "operationId": "SettlementAccountsService_GetSettlementAccountTransaction"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}/withdrawals": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Lists the withdrawals for a specific settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts",
                    "BETA"
                ],
                "summary": "List withdrawals",
                "operationId": "SettlementAccountsService_ListSettlementAccountWithdrawals"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Creates a withdrawal for the specific transaction, settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts",
                    "BETA"
                ],
                "summary": "Create withdrawal",
                "operationId": "SettlementAccountsService_CreateSettlementAccountWithdrawal"
            }
        },
        "/payment/v1/merchants/{merchantId}/accounts/{accountId}/withdrawals/{withdrawalId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "settlement-accounts:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts:readonly"
                        ]
                    },
                    {
                        "OAuth2Client": [
                            "settlement-accounts"
                        ],
                        "OAuth2OrgUser": [
                            "settlement-accounts"
                        ]
                    }
                ],
                "description": "Retrieves a specific withdrawal for a specific settlement account and merchant.",
                "tags": [
                    "Payment.Settlement Accounts",
                    "BETA"
                ],
                "summary": "Get withdrawal",
                "operationId": "SettlementAccountsService_GetSettlementAccountWithdrawal"
            }
        },
        "/payment/v1/settlement-account-payment-requests": {
            "post": {
                "security": [
                    {
                        "OAuth2Client": [
                            "payment:write"
                        ]
                    }
                ],
                "description": "Creates a payment request and sends the money to a specific settlement account for the specified currency.\nNote: in order to utilize this endpoint you need to have been onboarded for Settlement Accounts.",
                "tags": [
                    "Payment.Settlement Accounts"
                ],
                "summary": "Create payment request",
                "operationId": "SettlementAccountPaymentRequestsService_CreateSettlementAccountPaymentRequest"
            }
        },
        "/risk/v1/expense-checks": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "expense-checks:readonly"
                        ]
                    }
                ],
                "description": "Lists expense checks.",
                "tags": [
                    "Risk.Expense Check"
                ],
                "summary": "List expense checks",
                "operationId": "ExpenseChecksService_ListExpenseChecks"
            },
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "expense-checks:create"
                        ]
                    }
                ],
                "description": "Creates an expense check report containing the expenses of an end-user.",
                "tags": [
                    "Risk.Expense Check"
                ],
                "summary": "Create an expense check report",
                "operationId": "ExpenseChecksService_CreateExpenseCheck"
            }
        },
        "/risk/v1/expense-checks/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "expense-checks:readonly"
                        ]
                    }
                ],
                "description": "Gets an expense check by id.",
                "tags": [
                    "Risk.Expense Check"
                ],
                "summary": "Get an expense check",
                "operationId": "ExpenseChecksService_GetExpenseCheck"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Client": [
                            "expense-checks:delete"
                        ]
                    }
                ],
                "description": "Deletes an expense check by id.",
                "tags": [
                    "Risk.Expense Check"
                ],
                "summary": "Delete an expense check",
                "operationId": "ExpenseChecksService_DeleteExpenseCheck"
            }
        },
        "/risk/v1/risk-insights": {
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "risk-insights:create"
                        ]
                    }
                ],
                "description": "Creates a request and returns the risk insights report id of an end-user as a JSON response.",
                "tags": [
                    "Risk.Risk Insights"
                ],
                "summary": "Create Risk Insights",
                "operationId": "RiskInsightsService_CreateRiskInsights"
            }
        },
        "/risk/v1/risk-insights/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "risk-insights:readonly"
                        ],
                        "OAuth2User": [
                            "risk-insights:readonly"
                        ]
                    }
                ],
                "description": "Get a risk insights report of a user.",
                "tags": [
                    "Risk.Risk Insights"
                ],
                "summary": "Get a Risk Insights",
                "operationId": "RiskInsightsService_GetRiskInsights"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Client": [
                            "risk-insights:delete"
                        ]
                    }
                ],
                "description": "Deletes a risk insights report by id.",
                "tags": [
                    "Risk.Risk Insights"
                ],
                "summary": "Delete a Risk Insights",
                "operationId": "RiskInsightsService_DeleteRiskInsights"
            }
        },
        "/v2/income-checks": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "income-checks:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "income-checks:readonly"
                        ]
                    }
                ],
                "description": "Lists income checks.",
                "tags": [
                    "Risk.Income Check"
                ],
                "summary": "List income checks",
                "operationId": "IncomeChecksService_ListIncomeChecks"
            },
            "post": {
                "security": [
                    {
                        "OAuth2User": [
                            "income-checks:create"
                        ]
                    }
                ],
                "description": "Creates a request and returns the income of an end-user as a JSON response.",
                "tags": [
                    "Risk.Income Check"
                ],
                "summary": "Create an income check",
                "operationId": "IncomeChecksService_CreateIncomeCheck"
            }
        },
        "/v2/income-checks/report-data/{reportId}": {},
        "/v2/income-checks/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "income-checks:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "income-checks:readonly"
                        ],
                        "OAuth2User": [
                            "income-checks:readonly"
                        ]
                    }
                ],
                "description": "Gets an income check by id.",
                "tags": [
                    "Risk.Income Check"
                ],
                "summary": "Get an income check",
                "operationId": "IncomeChecksService_GetIncomeCheck"
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Client": [
                            "income-checks:delete"
                        ],
                        "OAuth2OrgUser": [
                            "income-checks:delete"
                        ]
                    }
                ],
                "description": "Deletes an income check by id.",
                "tags": [
                    "Risk.Income Check"
                ],
                "summary": "Delete an income check",
                "operationId": "IncomeChecksService_DeleteIncomeCheck"
            }
        },
        "/v2/income-checks/{id}:generate-pdf": {
            "get": {
                "security": [
                    {
                        "OAuth2Client": [
                            "income-checks:readonly"
                        ],
                        "OAuth2OrgUser": [
                            "income-checks:readonly"
                        ]
                    }
                ],
                "description": "Generates an income check as PDF.",
                "tags": [
                    "Risk.Income Check"
                ],
                "summary": "Generate an income check as PDF",
                "operationId": "IncomeChecksService_GeneratePdf"
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
          "type": "apiKey",
          "name": "Authorization",
          "in": "header",
          "description": "Enter your bearer token in the format Bearer {token}"
        },
        "OAuth2": {
            "type": "oauth2",
            "in": "header",
            "flow": "accessCode",
            "authorizationUrl": "https://api.tink.com/api/v1/oauth/authorization-grant",
            "tokenUrl": "https://api.tink.com/api/v1/oauth/token",
            "scopes": {
                "budgets:read": "budgets:read",
                "budgets:write": "budgets:write",
                "calendar:read": "calendar:read",
                "cost-of-living:read": "cost-of-living:read",
                "credentials:read": "credentials:read",
                "credentials:refresh": "credentials:refresh",
                "credentials:write": "credentials:write",
                "provider-consents:read": "provider-consents:read",
                "provider-consents:write": "provider-consents:write",
                "savings-goals:read": "savings-goals:read",
                "savings-goals:write": "savings-goals:write",
                "statistics:read": "statistics:read",
                "subscriptions:read": "subscriptions:read",
                "transactions:read": "transactions:read",
                "user:web_hooks": "user:web_hooks"
            }
        },
        "OAuth2Client": {
            "type": "oauth2",
            "in": "header",
            "flow": "application",
            "tokenUrl": "https://api.tink.com/api/v1/oauth/token",
            "scopes": {
                "account-verification-reports:read": "account-verification-reports:read",
                "accounts.balances:readonly": "accounts.balances:readonly",
                "accounts:read": "accounts:read",
                "accounts:write": "accounts:write",
                "authorization:grant": "authorization:grant",
                "authorization:revoke": "authorization:revoke",
                "bulk-payment:read": "bulk-payment:read",
                "bulk-payment:write": "bulk-payment:write",
                "business-account-verification-reports:read": "business-account-verification-reports:read",
                "consents": "consents",
                "consents:readonly": "consents:readonly",
                "enrichment.on-demand": "enrichment.on-demand",
                "enrichment.transactions": "enrichment.transactions",
                "enrichment.transactions:readonly": "enrichment.transactions:readonly",
                "expense-checks:delete": "expense-checks:delete",
                "expense-checks:readonly": "expense-checks:readonly",
                "income-checks:delete": "income-checks:delete",
                "income-checks:readonly": "income-checks:readonly",
                "link-session:write": "link-session:write",
                "mandate-payments": "mandate-payments",
                "mandate-payments:readonly": "mandate-payments:readonly",
                "merchants": "merchants",
                "merchants:readonly": "merchants:readonly",
                "payment:read": "payment:read",
                "payment:write": "payment:write",
                "providers:read": "providers:read",
                "reports-generation-jobs:readonly": "reports-generation-jobs:readonly",
                "risk-insights:delete": "risk-insights:delete",
                "risk-insights:readonly": "risk-insights:readonly",
                "settlement-accounts": "settlement-accounts",
                "settlement-accounts:readonly": "settlement-accounts:readonly",
                "transaction-reports:readonly": "transaction-reports:readonly",
                "transactions:write": "transactions:write",
                "user:create": "user:create",
                "user:read": "user:read",
                "webhook-endpoints": "webhook-endpoints"
            }
        },
        "OAuth2User": {
            "type": "oauth2",
            "in": "header",
            "flow": "accessCode",
            "authorizationUrl": "https://api.tink.com/api/v1/oauth/authorization-grant",
            "tokenUrl": "https://api.tink.com/api/v1/oauth/token",
            "scopes": {
                "account-verification-reports:read": "account-verification-reports:read",
                "accounts.balances:readonly": "accounts.balances:readonly",
                "accounts.parties:readonly": "accounts.parties:readonly",
                "accounts:read": "accounts:read",
                "accounts:write": "accounts:write",
                "balance-refresh": "balance-refresh",
                "balance-refresh:readonly": "balance-refresh:readonly",
                "balances:read": "balances:read",
                "budgets-bfm": "budgets-bfm",
                "bulk-payment:read": "bulk-payment:read",
                "bulk-payment:write": "bulk-payment:write",
                "business-account-verification-reports:read": "business-account-verification-reports:read",
                "cash-flow": "cash-flow",
                "consents": "consents",
                "consents:readonly": "consents:readonly",
                "credentials:read": "credentials:read",
                "credentials:write": "credentials:write",
                "enrichment.merchant": "enrichment.merchant",
                "enrichment.sustainability": "enrichment.sustainability",
                "enrichment.transactions": "enrichment.transactions",
                "enrichment.transactions:readonly": "enrichment.transactions:readonly",
                "expense-checks:create": "expense-checks:create",
                "financial-calendar": "financial-calendar",
                "financial-calendar:readonly": "financial-calendar:readonly",
                "identities:readonly": "identities:readonly",
                "identity:read": "identity:read",
                "income-checks:create": "income-checks:create",
                "income-checks:readonly": "income-checks:readonly",
                "insights:read": "insights:read",
                "insights:write": "insights:write",
                "investment-accounts:readonly": "investment-accounts:readonly",
                "investments:read": "investments:read",
                "link-session:read": "link-session:read",
                "loan-accounts:readonly": "loan-accounts:readonly",
                "payment:read": "payment:read",
                "providers:read": "providers:read",
                "risk-insights:create": "risk-insights:create",
                "risk-insights:readonly": "risk-insights:readonly",
                "transactions.recurring:read": "transactions.recurring:read",
                "transactions:categorize": "transactions:categorize",
                "transactions:read": "transactions:read",
                "transactions:write": "transactions:write",
                "user:delete": "user:delete",
                "user:read": "user:read",
                "user:write": "user:write"
            }
        }
    },
    "tags": [
        {
            "name": "BETA"
        },
        {
            "name": "Connectivity v1.Balance Refresh"
        },
        {
            "name": "Connectivity v1.Credentials"
        },
        {
            "name": "Connectivity v1.Provider"
        },
        {
            "name": "Connectivity v1.Provider Consent"
        },
        {
            "name": "Connectivity v2.Authorization"
        },
        {
            "name": "Connectivity v2.Consent"
        },
        {
            "name": "Connectivity v2.Consent Templates"
        },
        {
            "name": "Connector.Account"
        },
        {
            "name": "Connector.Transaction"
        },
        {
            "name": "Data v1.Account"
        },
        {
            "name": "Data v1.Account Verification"
        },
        {
            "name": "Data v1.Business Account Verification"
        },
        {
            "name": "Data v1.Identity"
        },
        {
            "name": "Data v1.Investment"
        },
        {
            "name": "Data v1.Loan"
        },
        {
            "name": "Data v1.Search"
        },
        {
            "name": "Data v1.Transaction"
        },
        {
            "name": "Data v2.Account"
        },
        {
            "name": "Data v2.Identity"
        },
        {
            "name": "Data v2.Investment"
        },
        {
            "name": "Data v2.Loan"
        },
        {
            "name": "Data v2.Transaction"
        },
        {
            "name": "Data v2.Transaction Report"
        },
        {
            "name": "ENTERPRISE"
        },
        {
            "name": "Enrichment.As a Service"
        },
        {
            "name": "Enrichment.Category"
        },
        {
            "name": "Enrichment.Enriched Transactions"
        },
        {
            "name": "Enrichment.Merchant Information.Brand"
        },
        {
            "name": "Enrichment.Merchant Information.Merchant"
        },
        {
            "name": "Enrichment.Recurring Transactions"
        },
        {
            "name": "Enrichment.Sustainability.Account Profiling"
        },
        {
            "name": "Enrichment.Sustainability.Insights"
        },
        {
            "name": "Enrichment.Sustainability.Market Average"
        },
        {
            "name": "Enrichment.Sustainability.Transactions"
        },
        {
            "name": "Events v1.Webhook"
        },
        {
            "name": "Events v2.Webhook"
        },
        {
            "name": "Finance Management.Actionable Insight"
        },
        {
            "name": "Finance Management.Budgets"
        },
        {
            "name": "Finance Management.Business Budgets"
        },
        {
            "name": "Finance Management.Cash flow"
        },
        {
            "name": "Finance Management.Cost of Living"
        },
        {
            "name": "Finance Management.Financial calendar"
        },
        {
            "name": "Finance Management.Notification"
        },
        {
            "name": "Finance Management.Savings Goals"
        },
        {
            "name": "Finance Management.Statistic"
        },
        {
            "name": "Finance Management.Subscriptions"
        },
        {
            "name": "General.Calendar"
        },
        {
            "name": "General.Category"
        },
        {
            "name": "General.OAuth"
        },
        {
            "name": "General.Reports Generation Jobs"
        },
        {
            "name": "General.Tink Link.Session"
        },
        {
            "name": "General.User"
        },
        {
            "name": "MULTI_TENANT"
        },
        {
            "name": "Partner Integration.Merchants"
        },
        {
            "name": "Payment.Bulk Payment"
        },
        {
            "name": "Payment.Cancellation"
        },
        {
            "name": "Payment.Mandate Payment"
        },
        {
            "name": "Payment.Payment Request"
        },
        {
            "name": "Payment.Settlement Accounts"
        },
        {
            "name": "REGION.US"
        },
        {
            "name": "Risk.Expense Check"
        },
        {
            "name": "Risk.Income Check"
        },
        {
            "name": "Risk.Risk Insights"
        },
        {
            "name": "SessionService"
        }
    ]
}